# Generated by Django 4.2.5 on 2023-11-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0002_alter_set_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
