# Generated by Django 4.2.5 on 2023-10-04 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_logs', '0002_exercise_rep_num_exercise_set_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 5, 19, 4, 774312, tzinfo=datetime.timezone.utc), verbose_name='date of exercise'),
        ),
    ]
