# Generated by Django 4.2.5 on 2023-10-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_logs', '0003_exercise_exercise_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date of exercise'),
        ),
    ]
