# Generated by Django 4.2.5 on 2023-10-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_logs', '0004_alter_exercise_exercise_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date of workout'),
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
