# Generated by Django 4.2.5 on 2023-10-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_logs', '0006_workout_user_alter_workout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
