# Generated by Django 4.2.5 on 2023-10-16 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_logs', '0007_alter_workout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of workout'),
        ),
    ]
