# Generated by Django 4.2.5 on 2023-10-21 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_logs', '0011_tag_stream_follow_workout_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
