# Generated by Django 4.2.5 on 2023-10-11 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise_logs', '0004_alter_exercise_exercise_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_text', models.CharField(max_length=200)),
                ('exercise_date', models.DateTimeField(auto_now_add=True, verbose_name='date of exercise')),
                ('weight_num', models.IntegerField(default=0)),
                ('weight_type', models.CharField(default='lb', max_length=200)),
                ('set_num', models.IntegerField(default=1)),
                ('rep_num', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercise_logs.workout')),
            ],
        ),
    ]
