# Generated by Django 4.2.5 on 2023-10-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='rep_num',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='set_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight_type',
            field=models.CharField(default='lb', max_length=200),
        ),
        migrations.DeleteModel(
            name='Set',
        ),
    ]
